apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  namespace: ingress-nginx
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: ingress-nginx
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/db-storage

