name: Build and deploy Informirajse Docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Backend image
      run: docker build -t anthony70/informirajse-app:latest . && docker push anthony70/informirajse-app:latest

    - name: Build and push UI image
      run: cd InformirajSe.UI && docker build -t anthony70/informirajse-app-ui:latest . && docker push anthony70/informirajse-app-ui:latest